<center>
    <img src="https://weclouddata.s3.amazonaws.com/images/logos/wcd_logo_new_2.png" width='20%'>
</center>

----------

<h1 align="center"> Exercise - Pandas Data Processing </h1>


----------

# Exercise 1
Load all the data files into Python

In [ ]:
%pip install pandas

In [1]:
import pandas as pd
import csv

In [22]:
sales = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimSalesOrder.csv', dtype={"CarrierTrackingNumber": str, "CustomerPONumber": str})
product = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimProduct.csv')
category = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimProductCategory.csv')
subcategory = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimProductSubCategory.csv')
customer = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimCustomer.csv')
reseller = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimReseller.csv')
date = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimDate.csv')
geography = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimGeography.csv')
territory = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimSalesTerritory.csv')

Look at each table to make sure they have been read the way you wanted

In [4]:
reseller

    ResellerKey;GeographyKey;ResellerAlternateKey;Phone;BusinessType;ResellerName;NumberEmployees;OrderFrequency;OrderMonth;FirstOrderYear;LastOrderYear;ProductLine;AddressLine1;AddressLine2;AnnualSales;BankName;MinPaymentType;MinPaymentAmount;AnnualRevenue;YearOpened
0    1;637;AW00000001;245-555-0173;Value Added Rese...
1    2;635;AW00000002;170-555-0127;Specialty Bike S...
2    3;584;AW00000003;279-555-0130;Warehouse;Advanc...
3    4;572;AW00000004;710-555-0173;Value Added Rese...
4    5;322;AW00000005;828-555-0186;Specialty Bike S...
..                                                 ...
696  697;601;AW00000697;774-555-0133;Value Added Re...
697  698;595;AW00000698;944-555-0148;Specialty Bike...
698  699;496;AW00000699;716-555-0123;Warehouse;Sens...
699  700;494;AW00000700;703-555-0158;Value Added Re...
700  701;41;AW00000701;674-555-0188;Warehouse;Futur...

[701 rows x 1 columns]

In [6]:
# The reseller file is semicolon separated, but reading it with sep=';'
# directly leaves row 700 misaligned. Requires some tinkering:
reseller = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimReseller.csv', sep=';')
reseller

,ResellerKey,GeographyKey,ResellerAlternateKey,Phone,BusinessType,ResellerName,NumberEmployees,OrderFrequency,OrderMonth,FirstOrderYear,LastOrderYear,ProductLine,AddressLine1,AddressLine2,AnnualSales,BankName,MinPaymentType,MinPaymentAmount,AnnualRevenue,YearOpened
0,1,637.0,AW00000001,245-555-0173,Value Added Reseller,A Bike Store,2.0,S,5.0,2011.0,2011.0,Road,2251 Elliot Avenue,NaN,300000.0,International Bank,NaN,NaN,30000.0,1974.0
1,2,635.0,AW00000002,170-555-0127,Specialty Bike Shop,Progressive Sports,10.0,A,5.0,2012.0,2013.0,Mountain,3207 S Grady Way,NaN,800000.0,International Security,1.0,NaN,80000.0,1976.0
2,3,584.0,AW00000003,279-555-0130,Warehouse,Advanced Bike Components,40.0,Q,6.0,2011.0,2013.0,Road,12345 Sterling Avenue,NaN,1500000.0,Primary International,2.0,NaN,150000.0,1978.0
3,4,572.0,AW00000004,710-555-0173,Value Added Reseller,Modular Cycle Systems,5.0,S,4.0,2011.0,2013.0,Road,800 Interchange Blvd.,Suite 2501,300000.0,United Security,3.0,600.0,30000.0,1980.0
4,5,322.0,AW00000005,828-555-0186,Specialty Bike Shop,Metropolitan Sports Supply,13.0,A,6.0,2012.0,2013.0,Road,482505 Warm Springs Blvd.,NaN,800000.0,Primary Bank & Reserve,NaN,NaN,80000.0,1982.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
696,697,601.0,AW00000697,774-555-0133,Value Added Reseller,Brakes and Gears,12.0,S,5.0,2011.0,2013.0,Mountain,9927 N. Main St.,NaN,800000.0,United Security,3.0,600.0,80000.0,1992.0
697,698,595.0,AW00000698,944-555-0148,Specialty Bike Shop,Western Bike Supplies,48.0,A,4.0,2011.0,2012.0,Road,566 S. Main,NaN,1500000.0,Primary Bank & Reserve,NaN,NaN,150000.0,1998.0
698,699,496.0,AW00000699,716-555-0123,Warehouse,Sensational Discount Store,80.0,Q,3.0,2013.0,2013.0,Road,6333 Cloverleaf Parkway,NaN,3000000.0,Guardian Bank,1.0,NaN,300000.0,1991.0
699,700,494.0,AW00000700,703-555-0158,Value Added Reseller,Underglaze and Finish Company,11.0,S,5.0,2013.0,2013.0,Road,8520 University City Blvd,NaN,800000.0,Reserve Security,2.0,NaN,80000.0,1997.0
700,701;41;AW00000701;674-555-0188;Warehouse;Futur...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# Fixed: read each line as a single column, then split on ';'

reseller = pd.read_csv('https://weclouddata.s3.amazonaws.com/datasets/retail/adventureworks/csv/DimReseller.csv', sep=',', header=None)
reseller =  reseller.loc[:,0].str.split(';', expand=True)
reseller

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,ResellerKey,GeographyKey,ResellerAlternateKey,Phone,BusinessType,ResellerName,NumberEmployees,OrderFrequency,OrderMonth,FirstOrderYear,LastOrderYear,ProductLine,AddressLine1,AddressLine2,AnnualSales,BankName,MinPaymentType,MinPaymentAmount,AnnualRevenue,YearOpened
1,1,637,AW00000001,245-555-0173,Value Added Reseller,A Bike Store,2,S,5,2011,2011,Road,2251 Elliot Avenue,,300000,International Bank,,,30000,1974
2,2,635,AW00000002,170-555-0127,Specialty Bike Shop,Progressive Sports,10,A,5,2012,2013,Mountain,3207 S Grady Way,,800000,International Security,1,,80000,1976
3,3,584,AW00000003,279-555-0130,Warehouse,Advanced Bike Components,40,Q,6,2011,2013,Road,12345 Sterling Avenue,,1500000,Primary International,2,,150000,1978
4,4,572,AW00000004,710-555-0173,Value Added Reseller,Modular Cycle Systems,5,S,4,2011,2013,Road,800 Interchange Blvd.,Suite 2501,300000,United Security,3,600,30000,1980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,697,601,AW00000697,774-555-0133,Value Added Reseller,Brakes and Gears,12,S,5,2011,2013,Mountain,9927 N. Main St.,,800000,United Security,3,600,80000,1992
698,698,595,AW00000698,944-555-0148,Specialty Bike Shop,Western Bike Supplies,48,A,4,2011,2012,Road,566 S. Main,,1500000,Primary Bank & Reserve,,,150000,1998
699,699,496,AW00000699,716-555-0123,Warehouse,Sensational Discount Store,80,Q,3,2013,2013,Road,6333 Cloverleaf Parkway,,3000000,Guardian Bank,1,,300000,1991
700,700,494,AW00000700,703-555-0158,Value Added Reseller,Underglaze and Finish Company,11,S,5,2013,2013,Road,8520 University City Blvd,,800000,Reserve Security,2,,80000,1997
701,701,41,AW00000701,674-555-0188,Warehouse,Future Bikes,81,Q,6,2012,2013,Road,"67255 - 8th Street N.E., Suite 350",,3000000,Guardian Bank,3,600,300000,1996

In [8]:
new_header = reseller.iloc[0] #grab the first row for the header
reseller = reseller[1:] #take the data less the header row
reseller.columns = new_header #set the header row as the df header
reseller

,ResellerKey,GeographyKey,ResellerAlternateKey,Phone,BusinessType,ResellerName,NumberEmployees,OrderFrequency,OrderMonth,FirstOrderYear,LastOrderYear,ProductLine,AddressLine1,AddressLine2,AnnualSales,BankName,MinPaymentType,MinPaymentAmount,AnnualRevenue,YearOpened
1,1,637,AW00000001,245-555-0173,Value Added Reseller,A Bike Store,2,S,5,2011,2011,Road,2251 Elliot Avenue,,300000,International Bank,,,30000,1974
2,2,635,AW00000002,170-555-0127,Specialty Bike Shop,Progressive Sports,10,A,5,2012,2013,Mountain,3207 S Grady Way,,800000,International Security,1,,80000,1976
3,3,584,AW00000003,279-555-0130,Warehouse,Advanced Bike Components,40,Q,6,2011,2013,Road,12345 Sterling Avenue,,1500000,Primary International,2,,150000,1978
4,4,572,AW00000004,710-555-0173,Value Added Reseller,Modular Cycle Systems,5,S,4,2011,2013,Road,800 Interchange Blvd.,Suite 2501,300000,United Security,3,600,30000,1980
5,5,322,AW00000005,828-555-0186,Specialty Bike Shop,Metropolitan Sports Supply,13,A,6,2012,2013,Road,482505 Warm Springs Blvd.,,800000,Primary Bank & Reserve,,,80000,1982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
697,697,601,AW00000697,774-555-0133,Value Added Reseller,Brakes and Gears,12,S,5,2011,2013,Mountain,9927 N. Main St.,,800000,United Security,3,600,80000,1992
698,698,595,AW00000698,944-555-0148,Specialty Bike Shop,Western Bike Supplies,48,A,4,2011,2012,Road,566 S. Main,,1500000,Primary Bank & Reserve,,,150000,1998
699,699,496,AW00000699,716-555-0123,Warehouse,Sensational Discount Store,80,Q,3,2013,2013,Road,6333 Cloverleaf Parkway,,3000000,Guardian Bank,1,,300000,1991
700,700,494,AW00000700,703-555-0158,Value Added Reseller,Underglaze and Finish Company,11,S,5,2013,2013,Road,8520 University City Blvd,,800000,Reserve Security,2,,80000,1997
701,701,41,AW00000701,674-555-0188,Warehouse,Future Bikes,81,Q,6,2012,2013,Road,"67255 - 8th Street N.E., Suite 350",,3000000,Guardian Bank,3,600,300000,1996

# Exercise 2
Which table should be used as the fact table?

fact table: contains all the data to be analyzed

dimension table: contains all the data which the data in the fact table can be analyzed by

In [9]:
sales.head()

,Channel,SalesOrderKey,SalesOrderLineKey,SalesOrderNumber,SalesOrderLineNumber,ResellerKey,CustomerKey,ProductKey,OrderDateKey,DueDateKey,...,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmount,FreightAmount,CarrierTrackingNumber,CustomerPONumber,RevisionNumber
0,Reseller,43659,43659001,SO43659,1,676,-1,349,20170702,20170712,...,0.0,0.0,1898.0944,1898.0944,2024.994,161.9995,50.6249,4911-403C-98,PO522145787,1
1,Reseller,43659,43659002,SO43659,2,676,-1,350,20170702,20170712,...,0.0,0.0,1898.0944,5694.2832,6074.982,485.9986,151.8746,4911-403C-98,PO522145787,1
2,Reseller,43659,43659003,SO43659,3,676,-1,351,20170702,20170712,...,0.0,0.0,1898.0944,1898.0944,2024.994,161.9995,50.6249,4911-403C-98,PO522145787,1
3,Reseller,43659,43659004,SO43659,4,676,-1,344,20170702,20170712,...,0.0,0.0,1912.1544,1912.1544,2039.994,163.1995,50.9999,4911-403C-98,PO522145787,1
4,Reseller,43659,43659005,SO43659,5,676,-1,345,20170702,20170712,...,0.0,0.0,1912.1544,1912.1544,2039.994,163.1995,50.9999,4911-403C-98,PO522145787,1

Check if there are any empty cells in this table

In [13]:
sales.isna()

,Channel,SalesOrderKey,SalesOrderLineKey,SalesOrderNumber,SalesOrderLineNumber,ResellerKey,CustomerKey,ProductKey,OrderDateKey,DueDateKey,...,UnitPriceDiscountPct,DiscountAmount,ProductStandardCost,TotalProductCost,SalesAmount,TaxAmount,FreightAmount,CarrierTrackingNumber,CustomerPONumber,RevisionNumber
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121248,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
121249,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
121250,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
121251,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
121252,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False

Checking the NA values:

In [16]:
# isna() - for checking the NA values
sales.isna().sum()

Channel              0
SalesOrderKey        0
SalesOrderNumber     0
ResellerKey          0
CustomerKey          0
ProductKey           0
OrderDateKey         0
SalesTerritoryKey    0
OrderQuantity        0
UnitPrice            0
TotalProductCost     0
SalesAmount          0
dtype: int64

Remove columns you don't think are useful

In [24]:
sales = sales.drop(['TaxAmount','FreightAmount','CarrierTrackingNumber','RevisionNumber','EmployeeKey','SalesOrderLineKey','SalesOrderLineNumber','CurrencyKey','CustomerPONumber','DiscountAmount','ProductStandardCost','PromotionKey','DueDateKey','ShipDateKey','ExtendedAmount','UnitPriceDiscountPct'],axis = 1)
sales

,Channel,SalesOrderKey,SalesOrderNumber,ResellerKey,CustomerKey,ProductKey,OrderDateKey,SalesTerritoryKey,OrderQuantity,UnitPrice,TotalProductCost,SalesAmount
0,Reseller,43659,SO43659,676,-1,349,20170702,5,1,2024.994,1898.0944,2024.994
1,Reseller,43659,SO43659,676,-1,350,20170702,5,3,2024.994,5694.2832,6074.982
2,Reseller,43659,SO43659,676,-1,351,20170702,5,1,2024.994,1898.0944,2024.994
3,Reseller,43659,SO43659,676,-1,344,20170702,5,1,2039.994,1912.1544,2039.994
4,Reseller,43659,SO43659,676,-1,345,20170702,5,1,2039.994,1912.1544,2039.994
...,...,...,...,...,...,...,...,...,...,...,...,...
121248,Internet,75122,SO75122,-1,15868,485,20200615,6,1,21.980,8.2205,21.980
121249,Internet,75122,SO75122,-1,15868,225,20200615,6,1,8.990,6.9223,8.990
121250,Internet,75123,SO75123,-1,18759,485,20200615,6,1,21.980,8.2205,21.980
121251,Internet,75123,SO75123,-1,18759,486,20200615,6,1,159.000,59.4660,159.000
121252,Internet,75123,SO75123,-1,18759,225,20200615,6,1,8.990,6.9223,8.990

# Exercise 3
Calculate total sales, costs, and gross profit

In [25]:
# Total sales
total_sales = sales['SalesAmount'].sum()
total_sales

np.float64(109809274.20299998)

In [26]:
# Total costs
total_costs = sales['TotalProductCost'].sum()
total_costs

np.float64(97257907.9547)

In [27]:
# Total gross profit = total sales - total costs
total_gprofit = total_sales - total_costs
total_gprofit

np.float64(12551366.248299986)

Make a new column in sales which contains gross profit by row

In [28]:
sales['GrossProfit'] = sales['SalesAmount'] - sales['TotalProductCost']

In [12]:
type(sales)

pandas.DataFrame

# Exercise 4
Find the top 5 largest orders placed by direct customers

In [29]:
sales['CustomerKey']

0            -1
1            -1
2            -1
3            -1
4            -1
          ...
121248    15868
121249    15868
121250    18759
121251    18759
121252    18759
Name: CustomerKey, Length: 121253, dtype: int64

In [30]:
# Filter out resellers
# (rows where CustomerKey is -1 are reseller orders, not direct customers)
sales_customer = sales[sales['CustomerKey'] != -1]
sales_customer

,Channel,SalesOrderKey,SalesOrderNumber,ResellerKey,CustomerKey,ProductKey,OrderDateKey,SalesTerritoryKey,OrderQuantity,UnitPrice,TotalProductCost,SalesAmount,GrossProfit
60855,Internet,43697,SO43697,-1,21768,310,20170701,6,1,3578.2700,2171.2942,3578.2700,1406.9758
60856,Internet,43698,SO43698,-1,28389,346,20170701,7,1,3399.9900,1912.1544,3399.9900,1487.8356
60857,Internet,43699,SO43699,-1,25863,346,20170701,1,1,3399.9900,1912.1544,3399.9900,1487.8356
60858,Internet,43700,SO43700,-1,14501,336,20170701,4,1,699.0982,413.1463,699.0982,285.9519
60859,Internet,43701,SO43701,-1,11003,346,20170701,9,1,3399.9900,1912.1544,3399.9900,1487.8356
...,...,...,...,...,...,...,...,...,...,...,...,...,...
121248,Internet,75122,SO75122,-1,15868,485,20200615,6,1,21.9800,8.2205,21.9800,13.7595
121249,Internet,75122,SO75122,-1,15868,225,20200615,6,1,8.9900,6.9223,8.9900,2.0677
121250,Internet,75123,SO75123,-1,18759,485,20200615,6,1,21.9800,8.2205,21.9800,13.7595
121251,Internet,75123,SO75123,-1,18759,486,20200615,6,1,159.0000,59.4660,159.0000,99.5340
121252,Internet,75123,SO75123,-1,18759,225,20200615,6,1,8.9900,6.9223,8.9900,2.0677

In [31]:
# How often does each direct customer appear? The length of this result is
# also the number of distinct direct customers
sales_customer['CustomerKey'].value_counts()

CustomerKey
11185    68
11300    67
11277    65
11262    63
11287    62
         ..
26369     1
24374     1
28789     1
21347     1
24704     1
Name: count, Length: 18484, dtype: int64

In [34]:
# METHOD 1: Using sort_values()
sales_customer.sort_values(by='SalesAmount', ascending=False)[['CustomerKey', 'SalesAmount', 'GrossProfit']].head(5)

       CustomerKey  SalesAmount  GrossProfit
60883        13258      3578.27    1406.9758
60944        11607      3578.27    1406.9758
60865        27616      3578.27    1406.9758
60874        16529      3578.27    1406.9758
60873        16483      3578.27    1406.9758

In [38]:
# METHOD 2: Using rank()
sales_customer['AmountRank'] = sales_customer['SalesAmount'].rank(ascending=False)
sales_customer.head(5)

,Channel,SalesOrderKey,SalesOrderNumber,ResellerKey,CustomerKey,ProductKey,OrderDateKey,SalesTerritoryKey,OrderQuantity,UnitPrice,TotalProductCost,SalesAmount,GrossProfit,AmountRank
60855,Internet,43697,SO43697,-1,21768,310,20170701,6,1,3578.2700,2171.2942,3578.2700,1406.9758,776.0
60856,Internet,43698,SO43698,-1,28389,346,20170701,7,1,3399.9900,1912.1544,3399.9900,1487.8356,1644.0
60857,Internet,43699,SO43699,-1,25863,346,20170701,1,1,3399.9900,1912.1544,3399.9900,1487.8356,1644.0
60858,Internet,43700,SO43700,-1,14501,336,20170701,4,1,699.0982,413.1463,699.0982,285.9519,13154.0
60859,Internet,43701,SO43701,-1,11003,346,20170701,9,1,3399.9900,1912.1544,3399.9900,1487.8356,1644.0

In [42]:
sales_customer[sales_customer['AmountRank'] <= 5][['CustomerKey', 'SalesAmount', 'GrossProfit', 'AmountRank']]

Empty DataFrame
Columns: [CustomerKey, SalesAmount, GrossProfit, AmountRank]
Index: []

Additional Exercise: Find the first and last names of the customers who placed these orders

In [43]:
# Looking up a single customer with a boolean mask
customer[customer['CustomerKey'] == 11433][['CustomerKey', 'FirstName', 'LastName']]

     CustomerKey FirstName LastName
433        11433   Maurice     Shan

In [44]:
# Looking up all five at once: isin() builds a boolean mask that is True
# wherever CustomerKey matches any value in the list
top_keys = sales_customer.sort_values(by='SalesAmount', ascending=False)['CustomerKey'].head(5)

customer[customer['CustomerKey'].isin(top_keys)][['CustomerKey', 'FirstName', 'LastName']]

       CustomerKey FirstName   LastName
607          11607   Clinton     Moreno
2258         13258      Anne  Dominguez
5483         16483    Warren        Jai
5529         16529  Jonathon  Gutierrez
16616        27616      Emma      Brown